excluded:
  - .build
  - .swiftpm
  - Package.swift

included: # case-sensitive paths to include during linting. `--path` is ignored if present
  - squadeasy

force_cast: error 
force_try:
  severity: error 

disabled_rules:
  - switch_case_alignment
  - nesting
  - identifier_name
  - type_name
  - implicit_getter
  - vertical_parameter_alignment
  - large_tuple
  - cyclomatic_complexity
  - private_over_fileprivate
  - line_length
  - multiple_closures_with_trailing_closure
  - type_body_length
  - file_length

reporter: "xcode"