name: worksapce
on:
  push:
    branches:
      - '**'
jobs:
  build_deploy_site:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      contents: read
      id-token: write

    steps:
    - name: deploy static site
      uses: kiarashvosough1999/docC-github-pages-deploy@v1.0.0